language: node_js
node_js:
  - '0.12'
sudo: false
env:
  global:
    # Matthias token for phosphorjs/phosphorjs.github.io
    - secure: "IhE0iXr0JHBYLPdRrhEYp3VX30EoJYMSxqbpyOuRYaRZQFv1wmTtEdhEuE1j76tPK8LvsTjgdVs3KqoRdt71gs+LT8jjzf1NYMH2prUt8k4cdcu8vmwISGiCkdXUb+2HoBdYG9lS59U72OZOI+wPIAOwDfLhn2MZO2htHbonKd8="
script:
  - git clone https://github.com/phosphorjs/phosphorjs.github.io.git build
  - node index.js '/'
  - cd build
  - git config --global user.email "travis@travis-ci.com"
  - git config --global user.name "Travis Bot"
  - git add *
  - git commit -am'build docs'
after_success: |
  if [[ $TRAVIS_PULL_REQUEST == false && $TRAVIS_BRANCH == 'source' ]]
  then
    pwd
    echo "Will push Documentation"
    git config credential.helper 'store --file=.git/credentials'
    echo "https://${GHTOKEN}:@github.com" > .git/credentials
    git push origin master:master
  else
    echo "Will only deploy docs build from master branch"
  fi

